### ISSUE TITLE
Non-plugin use requires manual update

### ISSUE THREAD

**Issue by DougInAMug** [Photosynthesis/MurmurationsAggregator#1]
I altered a murmurations json file https://kanthaus.online/media/murmurations_node.json to see if the aggregator would automatically pick it up. After waiting two days, I guessed it wouldn't. My suspicion was confirmed when I resubmitted the json url https://murmurations.network/index-submission/ and it updated in about one minute.

Did you think about automatic pinging?

I think it's low priority, because if you have the skills not to use wordpress, I guess you're capable of remembering to manually trigger murmurations the infrequent times that you do.

**Comment by Photosynthesis** [comment]
Hey @DougInAMug it's been a while! I'm belatedly closing this issue here because it's more related to the index/services than the Wordpress aggregator. But, it's an interesting idea. I think the way this would be implemented would be via a sort of crawler that would could continuously go through profiles checking if they are still active and whether they've been updated.
